FROM node:23.9.0-bookworm-slim

WORKDIR /issassembler-front-sandbox/app-web

# install elm
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y git
RUN curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
RUN gunzip elm.gz
RUN chmod +x elm
RUN mv elm /usr/local/bin

COPY . .

RUN npm install
RUN npx -y elm-tooling install
RUN npx -y playwright@1.51.0 install --with-deps

CMD ["npm", "run", "dev"]

EXPOSE 49518
