services:
  reverse-proxy:
    build: 
      context: ../../
      dockerfile: ./reverse-proxy/Dockerfile
    ports:
      - "8000:80"
    networks:
      - internal_network
  backend:
    ports:
      - "49922"
    networks:
      - internal_network
  app-web-nginx:
    build:
      context: ../../
      dockerfile: ./infra/Dockerfile
    ports:
      - "49518"
    networks:
      - internal_network
networks:
  internal_network:
    driver: bridge
