# add workflows label
workflows:
- changed-files: ['.github/workflows/**/*']

# add stop-merge label if base-branch is not develop
stop-merge:
- base-branch: ['!develop']

feature:
- changed-files: ['src/**/*.elm']
