services:
  reverse-proxy:
    build:
      context: ../../../reverse-proxy/
      dockerfile: ../../../reverse-proxy/dockerfile/Dockerfile.production
    ports:
      - "8000:80"
    networks:
      - internal_network
  backend:
    ports:
      - "49922"
    networks:
      - internal_network
  app-web:
    build:
      context: ../../../app-web/
      dockerfile: ../../../docker/app-web/dockerfile/Dockerfile.production
    ports:
      - "49518"
    networks:
      - internal_network
networks:
  internal_network:
    driver: bridge
