services:
  reverse-proxy:
    build:
      context: ../../reverse-proxy/
      dockerfile: ./dockerfile/Dockerfile.development
    ports:
      - "8000:80"
  app-web:
    build:
      context: ../../app-web/
      dockerfile: ./dockerfile/Dockerfile.development
    ports:
      - "49518"
    volumes:
      - ../../app-web/:/app-web:rw
  backend:
    ports:
      - "49922"
    volumes:
      - ../../backend/:/backend:rw
