services:
  reverse-proxy:
    build:
      context: ../../reverse-proxy/
      dockerfile: ./dockerfile/Dockerfile.production
    ports:
      - "80:80" 
  backend:
    ports:
      - "49922"
  app-web:
    build:
      context: ../../app-web/
      dockerfile: ./dockerfile/Dockerfile.production
    ports:
      - "49518"
