name: check-task
on:
  issue_comment:
    types: [edited]
jobs:
  pr_commented:
    name: PR comment
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: make-destination-branch-name
        run: |
          gh api /repos/${{github.repository}}/pulls/${{github.event.issue.number}} |
          jq .head.ref |
          xargs -IVAL echo  "branch_name=VAL" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: declare comment_id
        run: |
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".id" |
          xargs printf "%s%s\n" "comment_id=" |
          xargs echo >> $GITHUB_ENV
      - name: declare comment_url 
        run: |
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".url" |
          xargs printf "%s%s\n" "comment_url=" |
          xargs echo >> $GITHUB_ENV
      - name: declare newest_comment_id
        run: |
          gh api /repos/${{github.repository}}/issues/${{github.event.issue.number}}/comments >> issue.json
          node ./script/getNewestComment.js issue.json | 
          jq ".id" |
          xargs printf "%s%s\n" "newest_comment_id=" |
          xargs echo >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: declare previous_task_count
        run: |
          echo '${{ toJson(github.event.changes) }}' | 
          jq ".body.from" |
          grep -oE "\- \[ \]|\- \[x\]" |
          wc -l |
          xargs printf "%s%s\n" "previous_task_count=" |
          xargs echo >> $GITHUB_ENV
      - name: declare current_task_count
        run: |
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".body" |
          grep -oE "\- \[ \]|\- \[x\]" |
          wc -l |
          xargs printf "%s%s\n" "current_task_count=" |
          xargs echo >> $GITHUB_ENV
      - name: declare finished_task_count
        run: |
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".body" |
          grep -oE "\- \[x\]" |
          wc -l |
          xargs printf "%s%s\n" "finished_task_count=" |
          xargs echo >> $GITHUB_ENV
      - name: declare unfinished_task_count
        run: |
          echo '${{ toJson(github.event.changes) }}' | 
          jq ".body.from" |
          grep -oE "\- \[ \]" |
          wc -l |
          xargs printf "%s%s\n" "unfinished_task_count=" |
          xargs echo >> $GITHUB_ENV
      - name: Throws an error if a task is not completed or if a completed task is added as new.
        if: ${{ env.finished_task_count != 1 || env.unfinished_task_count != 1 || env.previous_task_count != 1 || env.current_task_count != 1 || env.newest_comment_id != env.comment_id }}
        run: exit 1
