name: code-check
on: 
  pull_request:
    branches:
      - "main"
      - "develop"
      - "**/main"
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm install
      - run: npm run test
  check-is-passed:
    runs-on: ubuntu-latest
    outputs:
      is_passed: ${{ steps.check_is_pass.outputs.is_pass }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm install
      - run: npm run dev &
      - run: npm run capture-actual
      - run: npm run compare
        continue-on-error: true
      - run: pkill elm
      - run: |
          node ./script/isPassed.js ../reg.json |
          xargs -IVAL echo "is_pass=VAL" >> $GITHUB_OUTPUT
        id: check_is_pass
        continue-on-error: true
  notify-vrt-result:
    runs-on: ubuntu-latest
    needs: check-is-passed
    # vrtが落ちた場合このjobを実行する
    steps:
      - name: aaa
        run: echo ${{needs.check-is-passed.outputs.is_passed}}
      - run: echo one
        if: needs.check-is-passed.outputs.is_passed == 1