name: check-task
on:
  issue_comment:
    types: [edited]
jobs:
  pr_commented:
    name: PR comment
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: gh api
        id: make-destination-branch-name
        run: |
          gh api /repos/${{github.repository}}/pulls/${{github.event.issue.number}} |
          jq .head.ref |
          xargs -IVAL echo  "branch_name=VAL" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.make-destination-branch-name.outputs.branch_name }}
          fetch-depth: 0
      - name: declare_comment_id
        run: |
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".id" |
          xargs echo |
          xargs printf "%s%s\n" "comment_id=" |
          xargs echo >> $GITHUB_ENV
            - name: declare_comment_id
      - name: declare_comment_url 
        run: |
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".issue_url |
          xargs echo |
          xargs printf "%s%s\n" "comment_url=" |
          xargs echo >> $GITHUB_ENV
      - name: declare_newest_comment_id
        run: |
          gh api /repos/${{github.repository}}/issues/${{github.event.issue.number}}/comments >> issue.json
          node ./script/getNewestComment.js issue.json | 
          jq ".id" |
          xargs printf "%s%s\n" "newest_comment_id=" |
          xargs echo >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        # jq ".id" | 
        # xargs -IVAL echo "newest_comment_id=VAL" >> $GITHUB_OUTPUT
      - run: |
          echo '${{ toJson(github.event.changes) }}' | jq ".body.from" | xargs echo "previous value: " >> message
      - run: |
          echo '${{ toJson(github.event.comment) }}' | jq ".body" | xargs echo "current value: " >> message
      - run: |
          echo '${{ toJson(github.event.changes) }}' | 
          jq ".body.from" |
          grep -oE "\- \[ \]|\- \[x\]" |
          wc -l |
          xargs echo |
          xargs printf "%s%s\n" "previous_task_count=" |
          xargs echo >> $GITHUB_ENV
      - run: |
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".body" |
          grep -oE "\- \[ \]|\- \[x\]" |
          wc -l |
          xargs echo |
          xargs printf "%s%s\n" "current_task_count=" |
          xargs echo >> $GITHUB_ENV
      - run: |
          echo '${{ toJson(github.event.comment) }}' | 
          jq ".body" |
          grep -oE "\- \[x\]" |
          wc -l |
          xargs echo |
          xargs printf "%s%s\n" "finished_task_count=" |
          xargs echo >> $GITHUB_ENV
      - run: |
          echo '${{ toJson(github.event.changes) }}' | 
          jq ".body.from" |
          grep -oE "\- \[ \]" |
          wc -l |
          xargs echo |
          xargs printf "%s%s\n" "unfinished_task_count=" |
          xargs echo >> $GITHUB_ENV
        env:
          NUMBER: ${{ github.event.issue.number }}
          COMMENT: ${{ toJson(github.event.comment) }}
          CHANGES: ${{ toJson(github.event.changes) }}
      - if: ${{ env.finished_task_count != 1 || env.unfinished_task_count != 1 || env.previous_task_count != 1 || env.current_task_count != 1 || env.newest_comment_id != env.comment_id }}
        run: exit 1
  update-expected-image:
    name: do update expected image
    needs: pr_commented
    runs-on: ubuntu-latest
    steps:
      # GitHub CLI api
      # https://cli.github.com/manual/gh_api
      - name: gh api
        id: make-destination-branch-name
        run: |
          gh api /repos/${{github.repository}}/pulls/${{github.event.issue.number}} |
          jq .head.ref |
          xargs -IVAL echo  "branch_name=VAL" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.make-destination-branch-name.outputs.branch_name }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: |
          npm install
          npm run dev &
          npm run capture-actual
          npm run update-expected
          pkill elm
      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add expected/src/.
          git commit -m "update expected"
          git push

