name: labeling

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  use-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - name: use-labeler
        uses: actions/labeler@v5.0.0-alpha.1
        with: 
          configuration-path: ".github/labeler-config.yml"
          sync-labels: true
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  stop-merge:
    runs-on: ubuntu-22.04
    needs: use-labeler
      
    steps:
      - name: declare has_label
        run: |
          echo has_label=${{ contains(github.event.pull_request.labels.*.name, 'stop-merge') }} >> $GITHUB_ENV
      - name: stop merge if has_label is true
        if: ${{ env.has_label == 'true' }} 
        run: |
          exit 1
          
