name: stop merge feature

on:
  pull_request:
    types:
      - "opened"
      - "labeled"
      - "unlabeled"
      - "edited"
      - "synchronize"
      - "ready_for_review"
      - "reopened"

jobs:
  stop-merge:
    runs-on: ubuntu-22.04
    steps:
      - name: declare has_label
        run: |
          echo has_label=${{ contains(github.event.pull_request.labels.*.name, 'stop-merge') }} >> $GITHUB_ENV
      - name: declare has_label
        run: |
          echo ${{ contains(github.event.pull_request.labels.*.name, 'stop-merge') }}
      - name: stop merge if has_label is true
        if: ${{ env.has_label }}
        run: |
          exit 1
