name: stop merge feature

on:
  pull_request:
    types:
      - "opened"
      - "labeled"
      - "unlabeled"
      - "edited"
      - "synchronize"
      - "ready_for_review"
      - "reopened"

jobs:
  check-blocked-merge:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: labelsを出力する
        run: |
          echo '${{ toJson(github.event.pull_request) }}' | jq ".labels"
      - name: labelsの存在判定をする
        run: |
          echo '${{ toJson(github.event.pull_request) }}' | 
          jq -c ".labels" |
          xargs -IVAL -0 node ./script/isExist.js 'VAL' stop-merge
          xargs -IVAL echo has_label=VAL >> $GITHUB_ENV
      - name: stop merge
        if: ${{ env.has_label == 1 }}
        run: |
          exit 1
