name: stop merge feature

on:
  pull_request:
    types:
      - "opened"
      - "labeled"
      - "unlabeled"
      - "edited"
      - "synchronize"
      - "ready_for_review"
      - "reopened"

jobs:
  check-blocked-merge:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: labelsを出力する
        run: |
          echo '${{ toJson(github.event.pull_request) }}' | jq ".labels"
      - name: labelsの存在判定をする
        run: |
          echo '${{ toJson(github.event.pull_request) }}' | jq -c ".labels" | xargs -IVAL -0 node ./script/isExist.js 'VAL' stop-merge
      - name: stop merge
        run: |
          exit 1

          '[
            {
              "color": "8B5C5C",
              "default": false,
              "description": "",
              "id": 6013871185,
              "name": "stop-merge",
              "node_id": "LA_kwDOI1RWtM8AAAABZnRkUQ",
              "url": "https://api.github.com/repos/ShebangDog/issassembler-front-sandbox/labels/stop-merge"
            }
          ]'