name: stop merge feature

on:
  pull_request:
    types:
      - "opened"
      - "labeled"
      - "unlabeled"
      - "edited"
      - "synchronize"
      - "ready_for_review"
      - "reopened"

jobs:
  check-blocked-merge:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: labelsを出力する
        run: |
          echo '${{ toJson(github.event.pull_request) }}' | jq ".labels"
      - name: labelsの存在判定をする
        run: |
          echo has_label=${{ contains(github.event.pull_request.labels.*.name, 'stop-merge') }} &&
          echo has_label=${{ contains(github.event.pull_request.labels.*.name, 'stop-merge') }} >> $GITHUB_ENV
      - name: stop merge
        run: |
          echo ${{ env.has_label }}
      - name: stop merge
        if: ${{ env.has_label == 1 }}
        run: |
          exit 1
