name: stop merge feature

on:
  pull_request:
    types:
      - "labeled"
      - "unlabeled"
  workflow_run: 
    workflows: [labeling]
    types: 
      completed

jobs:
  stop-merge:
    runs-on: ubuntu-22.04
    steps:
      - name: debug
        run: |
          echo ${{ github.event_name }} &&
          echo ${{ toJson(github.event_path) }} &&
          echo ${{ toJson(github.event.pull_request.labels.*.name) }}
      - name: declare has_label
        run: |
          echo has_label=${{ contains(github.event.pull_request.labels.*.name, 'stop-merge') }} >> $GITHUB_ENV
      - name: stop merge if has_label is true
        if: ${{ env.has_label == 'true' }} 
        run: |
          exit 1
