name: stop merge feature

defaults:
  run:
    working-directory: ./script
on:
  pull_request:
    types:
      - "opened"
      - "labeled"
      - "unlabeled"
      - "edited"
      - "synchronize"
      - "ready_for_review"
      - "reopened"

jobs:
  check-blocked-merge:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: labelsを出力する
        run: |
          echo '${{ toJson(github.event.pull_request) }}' | jq ".labels"
      - name: labelsの存在判定をする
        run: |
          echo '${{ toJson(github.event.pull_request) }}' | jq ".labels" | xargs -IVAL node ./isExist.js VAL stop-merge
      - name: stop merge
        run: |
          exit 1
